language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - python --version
  - pip install coverage
install:
  - pip install -r requirements.txt
script:
  - coverage run -m tests.parser -v all
after_script:
  - coverage report